companies = [
 ('Delvia Technologies ApS', 'mail.delvia.com'),
 ('Blyxon', 'blyxon.com'),
 ('Joriera Apparel', 'joriera.net'),
 ('Graum Group B.V.', 'mail.graum.org'),
 ('Nexia Toys', 'nexia.net'),
 ('Javeno Consulting', 'javeno.org'),
 ('Hivear', 'mail.hivear.net'),
 ('Dovix', 'mail.dovix.io'),
 ('Elvoeva Sàrl', 'mail.elvoeva.io'),
 ('Xeryx', 'mail.xeryx.com'),
 ('Gravel', 'gravel.org'),
 ('Cinano PLC', 'cinano.com'),
 ('Yural Audio Ltd.', 'yural.io'),
 ('Kalea Motors Ltd', 'kalea.net'),
 ('Graera Pharma AS', 'mail.graera.com'),
 ('Triaar', 'mail.triaar.com'),
 ('Galer Stone', 'mail.galer.io'),
 ('Kinel Games', 'mail.kinel.org'),
 ('Arceora', 'mail.arceora.net'),
 ('Lyneva Steel', 'mail.lyneva.net'),
 ('Glaeno Sports', 'glaeno.com'),
 ('Galo', 'galo.io'),
 ('Plenet Logistics', 'plenet.com'),
 ('Pival', 'pival.io'),
 ('Fenos', 'mail.fenos.io'),
 ('Oryor Ventures S.A.', 'mail.oryor.org'),
 ('Clyor', 'clyor.net'),
 ('Blyxer Beverages', 'mail.blyxer.org'),
 ('Alvar Beverages', 'alvar.org'),
 ('Nivix Robotics Inc.', 'mail.nivix.com'),
 ('Klevora Group', 'klevora.io'),
 ('Yunero', 'yunero.net'),
 ('Joriia Security Inc.', 'mail.joriia.org'),
 ('Lyntexo Systems', 'mail.lyntexo.com'),
 ('Triaion Inc.', 'mail.triaion.io'),
 ('Tivon Electronics Inc.', 'tivon.net'),
 ('Blyxer ApS', 'blyxer.com'),
 ('Rivio', 'mail.rivio.net'),
 ('Invis Fashion AG', 'mail.invis.com'),
 ('Hivea Advisors', 'mail.hivea.net'),
 ('Harar Retail Sp. z o.o.', 'mail.harar.net'),
 ('Luneno Group Pvt Ltd', 'mail.luneno.io'),
 ('Alvon', 'alvon.io'),
 ('Briero Print AS', 'mail.briero.io'),
 ('Lunono Labs S.L.', 'lunono.org'),
 ('Gravion ApS', 'mail.gravion.io'),
 ('Novix', 'mail.novix.io'),
 ('Nimium Health AG', 'nimium.io'),
 ('Umbeno Print', 'umbeno.org'),
 ('Javeno', 'mail.javeno.org'),
 ('Coreva LLC', 'mail.coreva.com'),
 ('Plenar S.L.', 'mail.plenar.io'),
 ('Nivis', 'mail.nivis.net'),
 ('Quarexo Electronics', 'mail.quarexo.io'),
 ('Fenen Systems Ltd.', 'fenen.io'),
 ('Yurex Bio', 'yurex.com'),
 ('Ivoeva Tools', 'mail.ivoeva.com'),
 ('Avereno Security PLC', 'avereno.net'),
 ('Vastis SA', 'mail.vastis.org'),
 ('Zalaora', 'zalaora.org'),
 ('Terayx', 'terayx.org'),
 ('Yolium', 'mail.yolium.com'),
 ('Yunia', 'mail.yunia.org'),
 ('Jorion', 'jorion.net'),
 ('Inzon Motors LLC', 'mail.inzon.com'),
 ('Wavex Marine S.L.', 'mail.wavex.io'),
 ('Xelal SL', 'xelal.org'),
 ('Graea Chem S.A.', 'mail.graea.net'),
 ('Kaio Sàrl', 'kaio.net'),
 ('Alvor', 'alvor.io'),
 ('Hareno Marine', 'hareno.net'),
 ('Nover Space SL', 'mail.nover.com'),
 ('Zerera Ltd', 'mail.zerera.com'),
 ('Grael Pvt Ltd', 'mail.grael.com'),
 ('Driora AG', 'driora.io'),
 ('Winet Chem Sp. z o.o.', 'winet.org'),
 ('Altyx Pvt Ltd', 'altyx.net'),
 ('Qarteno', 'mail.qarteno.org'),
 ('Winix Ltd.', 'mail.winix.org'),
 ('Lynia Research GmbH', 'lynia.org'),
 ('Roveexo Devices', 'roveexo.net'),
 ('Xelono Marine S.L.', 'mail.xelono.com'),
 ('Jorier Apparel', 'jorier.io'),
 ('Viryn LLC', 'mail.viryn.org'),
 ('Qalino', 'mail.qalino.net'),
 ('Javion Security Ltd.', 'mail.javion.com'),
 ('Rendeva', 'rendeva.org'),
 ('Hivet', 'hivet.net'),
 ('Zalao', 'mail.zalao.org'),
 ('Praeal Chem', 'praeal.net'),
 ('Upla AB', 'upla.io'),
 ('Aveono B.V.', 'mail.aveono.io'),
 ('Zenivo Retail', 'mail.zenivo.org'),
 ('Lynto', 'lynto.net'),
 ('Hivum Capital LLC', 'mail.hivum.org'),
 ('Meria ApS', 'mail.meria.net'),
 ('Cintaa Capital', 'cintaa.com'),
 ('Quaris Inc.', 'quaris.io'),
 ('Novex', 'mail.novex.org'),
 ('Lazex AS', 'lazex.io'),
 ('Quaron', 'mail.quaron.com'),
 ('Kinium', 'kinium.io'),
 ('Javio Design', 'mail.javio.org'),
 ('Rivex', 'mail.rivex.io'),
 ('Elvix', 'mail.elvix.io'),
 ('Triaeno SL', 'mail.triaeno.net'),
 ('Jorea Print Sp. z o.o.', 'mail.jorea.com'),
 ('Yunar', 'mail.yunar.io'),
 ('Delyx AS', 'mail.delyx.io'),
 ('Kaiora Advisors Kft.', 'mail.kaiora.io'),
 ('Zena S.A.', 'zena.com'),
 ('Klevexo Dynamics', 'mail.klevexo.io'),
 ('Ossiera Sports', 'ossiera.org'),
 ('Niveva AS', 'mail.niveva.net'),
 ('Praeino s.r.o.', 'mail.praeino.io'),
 ('Triayx Software', 'triayx.net'),
 ('Arceo Retail', 'mail.arceo.org'),
 ('Qalora Sports SA', 'qalora.com'),
 ('Zenvium Ltd', 'mail.zenvium.org'),
 ('Zeros AG', 'mail.zeros.com'),
 ('Lunaen B.V.', 'mail.lunaen.io'),
 ('Vasto', 'mail.vasto.io'),
 ('Lazal', 'mail.lazal.io'),
 ('Ossiono Pte Ltd', 'mail.ossiono.org'),
 ('Lunaium', 'mail.lunaium.com'),
 ('Clyen', 'clyen.com'),
 ('Lyntero NV', 'lyntero.org'),
 ('Averea B.V.', 'mail.averea.io'),
 ('Ossiet', 'ossiet.org'),
 ('Quaris Pharma Ltd.', 'quaris.net'),
 ('Ivorera SARL', 'mail.ivorera.io'),
 ('Lynino', 'lynino.net'),
 ('Borel', 'borel.io'),
 ('Gravexo Gardens', 'mail.gravexo.net'),
 ('Glaion Motors', 'mail.glaion.org'),
 ('Ossiis', 'ossiis.io'),
 ('Roveos Pvt Ltd', 'roveos.net'),
 ('Glaix Pharma', 'glaix.io'),
 ('Queleva Apparel ApS', 'queleva.net'),
 ('Zeneno', 'zeneno.com'),
 ('Invis Steel', 'mail.invis.org'),
 ('Kinara', 'kinara.io'),
 ('Jolal Kft.', 'jolal.org'),
 ('Lazono Pvt Ltd', 'mail.lazono.com'),
 ('Uvinon Cloud', 'mail.uvinon.org'),
 ('Uvinon Marine AG', 'uvinon.org'),
 ('Gravera', 'gravera.com'),
 ('Zerea Sports', 'mail.zerea.net'),
 ('Lazyx Analytics', 'mail.lazyx.io'),
 ('Gravora Bio Sp. z o.o.', 'mail.gravora.com'),
 ('Triia', 'mail.triia.com'),
 ('Triea Finance', 'mail.triea.org'),
 ('Praeen', 'praeen.org'),
 ('Soleno Devices', 'mail.soleno.io'),
 ('Kinel Lighting NV', 'mail.kinel.io'),
 ('Hiveen', 'mail.hiveen.io'),
 ('Calo Consulting AG', 'mail.calo.com'),
 ('Inzal PLC', 'mail.inzal.net'),
 ('Lyntos Logistics AS', 'mail.lyntos.io'),
 ('Averer Design', 'averer.io'),
 ('Nexio Green S.A.', 'mail.nexio.net'),
 ('Uvinexo', 'mail.uvinexo.io'),
 ('Dovyn Maritime', 'dovyn.net'),
 ('Mavivo', 'mail.mavivo.io'),
 ('Jorera Motors AS', 'jorera.org'),
 ('Zyphel Sp. z o.o.', 'mail.zyphel.org'),
 ('Harex Steel', 'mail.harex.com'),
 ('Blyxis', 'mail.blyxis.com'),
 ('Triion', 'mail.triion.io'),
 ('Mavivo Motors BV', 'mavivo.com'),
 ('Lyntino Supply Inc.', 'lyntino.io'),
 ('Waveva Pharma', 'waveva.io'),
 ('Hival', 'hival.net'),
 ('Yuna Sp. z o.o.', 'mail.yuna.net'),
 ('Oryium', 'oryium.io'),
 ('Lazel Devices', 'lazel.com'),
 ('Rivenis Robotics', 'mail.rivenis.org'),
 ('Ivorora Gardens', 'ivorora.com'),
 ('Jorion Analytics s.r.o.', 'mail.jorion.org'),
 ('Dovion', 'dovion.org'),
 ('Fluxara', 'mail.fluxara.com'),
 ('Wavivo', 'mail.wavivo.io'),
 ('Tivia', 'tivia.org'),
 ('Brixyn Electronics Pte Ltd', 'brixyn.io'),
 ('Winos Tools', 'mail.winos.com'),
 ('Ivorium', 'ivorium.io'),
 ('Nexalex SL', 'mail.nexalex.io'),
 ('Gravum Lighting', 'gravum.org'),
 ('Yolyx', 'yolyx.net'),
 ('Triyn', 'triyn.net'),
 ('Quario Ventures Ltd', 'mail.quario.com'),
 ('Plenea', 'plenea.net'),
 ('Quelyn Ltd.', 'mail.quelyn.io'),
 ('Delea Advisors', 'delea.com'),
 ('Kleval s.r.o.', 'mail.kleval.org'),
 ('Averia ApS', 'mail.averia.com'),
 ('Fenano', 'mail.fenano.net'),
 ('Senvora Textiles SA', 'senvora.org'),
 ('Umbis', 'umbis.io'),
 ('Cineno Cloud', 'mail.cineno.com'),
 ('Novix', 'novix.io'),
 ('Zenor Sàrl', 'zenor.io'),
 ('Fraxeva Pvt Ltd', 'mail.fraxeva.com'),
 ('Moneno PLC', 'moneno.io'),
 ('Monum Security AB', 'monum.org'),
 ('Ivorora Dynamics B.V.', 'ivorora.net'),
 ('Altal Green SA', 'altal.io'),
 ('Quelora', 'mail.quelora.org'),
 ('Yunion', 'mail.yunion.net'),
 ('Rendum Fashion GmbH', 'mail.rendum.com'),
 ('Trial Print', 'mail.trial.io'),
 ('Harara Print Ltd.', 'harara.org'),
 ('Rendono Sàrl', 'mail.rendono.com'),
 ('Arceix Marine', 'arceix.org'),
 ('Joryn Lighting', 'joryn.net'),
 ('Virar NV', 'mail.virar.com'),
 ('Jolono Motors', 'mail.jolono.com'),
 ('Quarino', 'quarino.com'),
 ('Elvor Labs AS', 'mail.elvor.io'),
 ('Alvis', 'alvis.org'),
 ('Yunino Supply B.V.', 'mail.yunino.io'),
 ('Javon', 'javon.com'),
 ('Epsal', 'mail.epsal.net'),
 ('Vela', 'vela.org'),
 ('Wava NV', 'mail.wava.net'),
 ('Epsor', 'mail.epsor.com'),
 ('Noveva', 'mail.noveva.net'),
 ('Velum SARL', 'velum.org'),
 ('Praeivo', 'mail.praeivo.net'),
 ('Otrivo Marine NV', 'mail.otrivo.org'),
 ('Drion Audio', 'mail.drion.io'),
 ('Nexala Care B.V.', 'mail.nexala.net'),
 ('Hivivo Studios', 'mail.hivivo.io'),
 ('Drien Design', 'drien.com'),
 ('Novum Advisors', 'mail.novum.net'),
 ('Harex Oy', 'harex.net'),
 ('Ivoora', 'mail.ivoora.net'),
 ('Ivoel Imaging', 'mail.ivoel.org'),
 ('Hiveal Logistics Sp. z o.o.', 'mail.hiveal.net'),
 ('Inzara', 'mail.inzara.net'),
 ('Joreva Oy', 'mail.joreva.net'),
 ('Zenvero Logistics', 'mail.zenvero.io'),
 ('Quelora Oy', 'mail.quelora.net'),
 ('Graven', 'graven.io'),
 ('Mavio Tools', 'mail.mavio.com'),
 ('Boris AB', 'boris.net'),
 ('Qarten Labs', 'qarten.com'),
 ('Solono B.V.', 'solono.io'),
 ('Vastivo Cloud', 'vastivo.org'),
 ('Kinen Dynamics', 'kinen.org'),
 ('Yura', 'mail.yura.net'),
 ('Lynteva SL', 'lynteva.net'),
 ('Calera Analytics', 'mail.calera.com'),
 ('Elvoea Steel', 'elvoea.com'),
 ('Ivoium Materials Pte Ltd', 'ivoium.net'),
 ('Zyphor Capital', 'mail.zyphor.io'),
 ('Xanos Design', 'mail.xanos.net'),
 ('Wavexo Materials B.V.', 'wavexo.net'),
 ('Delvia NV', 'delvia.net'),
 ('Zeria', 'zeria.io'),
 ('Kalmyn', 'kalmyn.org'),
 ('Virum Textiles', 'mail.virum.io'),
 ('Fluxio Systems', 'mail.fluxio.org'),
 ('Nexara', 'nexara.io'),
 ('Rendor Stone', 'rendor.com'),
 ('Dovum Beverages', 'mail.dovum.com'),
 ('Galeno Ltd.', 'mail.galeno.com'),
 ('Boreva', 'mail.boreva.net'),
 ('Gravel Technologies', 'mail.gravel.io'),
 ('Triaor', 'triaor.org'),
 ('Yunino', 'yunino.net'),
 ('Rivenium Gardens AS', 'rivenium.com'),
 ('Quarea Kft.', 'quarea.org'),
 ('Valeva Engineering', 'mail.valeva.io'),
 ('Pivel Electronics Ltd.', 'pivel.com'),
 ('Zeret Maritime s.r.o.', 'mail.zeret.net'),
 ('Altor Studios', 'altor.net'),
 ('Borora Print S.L.', 'mail.borora.com'),
 ('Tivon AS', 'tivon.io'),
 ('Rivex Digital', 'rivex.net'),
 ('Xelero ApS', 'xelero.com'),
 ('Xanyn', 'mail.xanyn.io'),
 ('Ossiel Digital Ltd', 'mail.ossiel.com'),
 ('Kaios Cloud PLC', 'kaios.com'),
 ('Quarar Imaging', 'quarar.org'),
 ('Zalaium Beverages Kft.', 'mail.zalaium.com'),
 ('Ossiis Foods', 'ossiis.org'),
 ('Roveen AG', 'roveen.com'),
 ('Novium', 'mail.novium.com'),
 ('Varis', 'mail.varis.org'),
 ('Corar GmbH', 'corar.io'),
 ('Galora Engineering Oy', 'mail.galora.com'),
 ('Teraano Lighting S.L.', 'teraano.net'),
 ('Cinen Ltd', 'mail.cinen.io'),
 ('Vaston Software', 'mail.vaston.com'),
 ('Quarex Apparel', 'quarex.net'),
 ('Uplivo', 'mail.uplivo.org'),
 ('Velum Design', 'mail.velum.org'),
 ('Valara Motors', 'mail.valara.com'),
 ('Klevino Bio', 'klevino.org'),
 ('Elvyn', 'elvyn.net'),
 ('Inzera Labs Sp. z o.o.', 'mail.inzera.org'),
 ('Jorora SL', 'jorora.net'),
 ('Lynero Materials', 'lynero.org'),
 ('Nimon Sàrl', 'mail.nimon.io'),
 ('Triaea NV', 'triaea.com'),
 ('Klevel', 'klevel.net'),
 ('Zerera Chem Ltd', 'zerera.net'),
 ('Xelexo Bio Sp. z o.o.', 'xelexo.net'),
 ('Trien Steel Sp. z o.o.', 'mail.trien.io'),
 ('Praear Systems', 'praear.com'),
 ('Hivex Pvt Ltd', 'hivex.io'),
 ('Corio Consulting', 'mail.corio.com'),
 ('Dovivo Care AS', 'mail.dovivo.com'),
 ('Somis Group', 'somis.io'),
 ('Deleno S.L.', 'deleno.net'),
 ('Lynara Security Sàrl', 'lynara.net'),
 ('Velora', 'velora.com'),
 ('Fluxora', 'mail.fluxora.io'),
 ('Uvinex AG', 'uvinex.io'),
 ('Arceium Tools AG', 'arceium.net'),
 ('Ivoren', 'mail.ivoren.io'),
 ('Jola AG', 'mail.jola.org'),
 ('Dovos', 'dovos.io'),
 ('Senvara SL', 'senvara.org'),
 ('Mava', 'mava.net'),
 ('Graval Ltd.', 'graval.com'),
 ('Monex', 'monex.io'),
 ('Inzen Shipping Sp. z o.o.', 'inzen.com'),
 ('Vastion', 'vastion.com'),
 ('Velo Fashion LLC', 'velo.io'),
 ('Coren Gardens Inc.', 'mail.coren.com'),
 ('Umbio Ltd', 'umbio.net'),
 ('Averero PLC', 'mail.averero.com'),
 ('Graara Pte Ltd', 'mail.graara.net'),
 ('Aveex Apparel Ltd.', 'mail.aveex.io'),
 ('Quelet', 'quelet.io'),
 ('Ivoano', 'mail.ivoano.org'),
 ('Plenyx Oy', 'mail.plenyx.com'),
 ('Quelyn Analytics B.V.', 'mail.quelyn.net'),
 ('Borion Kft.', 'mail.borion.net'),
 ('Delvix Fashion S.A.', 'mail.delvix.io'),
 ('Varel Logistics SARL', 'varel.io'),
 ('Cintaex Labs', 'cintaex.io'),
 ('Triaex', 'mail.triaex.com'),
 ('Fenex Games PLC', 'fenex.io'),
 ('Zyphea B.V.', 'zyphea.org'),
 ('Borio Ltd', 'borio.io'),
 ('Nivora Print', 'nivora.io'),
 ('Graer AG', 'mail.graer.org'),
 ('Nexea Marine AS', 'mail.nexea.org'),
 ('Prisia Capital Sàrl', 'mail.prisia.net'),
 ('Coris Toys s.r.o.', 'coris.net'),
 ('Averea Robotics', 'averea.org'),
 ('Lynero', 'lynero.net'),
 ('Mavium Devices', 'mavium.net'),
 ('Mavara Pets Inc.', 'mavara.io'),
 ('Brixum', 'brixum.com'),
 ('Avera AB', 'avera.net'),
 ('Lynton Analytics SL', 'lynton.com'),
 ('Triea S.L.', 'triea.com'),
 ('Yolara SL', 'yolara.io'),
 ('Varyx Research', 'mail.varyx.com'),
 ('Rivera AB', 'mail.rivera.com'),
 ('Senvum', 'senvum.com'),
 ('Zyphor Labs', 'zyphor.org'),
 ('Quaret SA', 'mail.quaret.io'),
 ('Kalera Logistics', 'mail.kalera.org'),
 ('Mavara SL', 'mavara.com'),
 ('Xereno AB', 'xereno.io'),
 ('Fluxara', 'fluxara.net'),
 ('Senvono Ltd', 'senvono.org'),
 ('Hivea Games S.A.', 'hivea.com'),
 ('Roveera', 'roveera.com'),
 ('Uvino Space Sàrl', 'uvino.org'),
 ('Oryis Tools', 'mail.oryis.org'),
 ('Graivo Foods', 'graivo.com'),
 ('Triio Lighting', 'triio.net'),
 ('Rendix Ltd', 'rendix.io'),
 ('Lyntal BV', 'lyntal.net'),
 ('Alvion Care BV', 'mail.alvion.org'),
 ('Senven Tools LLC', 'senven.org'),
 ('Zenvex Networks AB', 'zenvex.io'),
 ('Zera', 'mail.zera.io'),
 ('Kinal Digital Ltd', 'kinal.net'),
 ('Tivia Shipping', 'mail.tivia.net'),
 ('Xania Motors ApS', 'mail.xania.io'),
 ('Yunos Pvt Ltd', 'mail.yunos.net'),
 ('Oryexo ApS', 'oryexo.net'),
 ('Lunara Labs SARL', 'mail.lunara.io'),
 ('Kalmum NV', 'kalmum.net'),
 ('Cinar', 'cinar.io'),
 ('Jorono Beverages Pvt Ltd', 'jorono.net'),
 ('Corivo', 'corivo.org'),
 ('Quaros', 'mail.quaros.net'),
 ('Briyn', 'mail.briyn.net'),
 ('Blyxen Oy', 'mail.blyxen.net'),
 ('Lunaa Health', 'mail.lunaa.com'),
 ('Jorium Home S.A.', 'mail.jorium.io'),
 ('Brixivo Ltd', 'mail.brixivo.com'),
 ('Javeva', 'javeva.net'),
 ('Roveion Ltd', 'roveion.net'),
 ('Ossiium', 'ossiium.org'),
 ('Xelum Beverages', 'mail.xelum.net'),
 ('Xanero GmbH', 'mail.xanero.net'),
 ('Qaleno AB', 'qaleno.org'),
 ('Galeva', 'galeva.org'),
 ('Kaio Care S.A.', 'mail.kaio.com'),
 ('Xanor Cloud', 'xanor.org'),
 ('Someno Pets B.V.', 'mail.someno.org'),
 ('Delion SARL', 'delion.org'),
 ('Lyntal Capital', 'mail.lyntal.com'),
 ('Zalaex Pharma', 'mail.zalaex.net'),
 ('Zenvexo', 'mail.zenvexo.com'),
 ('Lazexo Space', 'mail.lazexo.org'),
 ('Nexalivo Data', 'nexalivo.io'),
 ('Lunaos Travel S.L.', 'lunaos.org'),
 ('Yurara Retail', 'yurara.io'),
 ('Delvix Retail S.A.', 'delvix.net'),
 ('Pivera Pharma NV', 'pivera.org'),
 ('Xelal Kft.', 'mail.xelal.com'),
 ('Hival Labs ApS', 'mail.hival.net'),
 ('Valera Lighting', 'mail.valera.org'),
 ('Vasteva Sàrl', 'vasteva.org'),
 ('Otral', 'otral.org'),
 ('Oryet', 'mail.oryet.io'),
 ('Teraono', 'teraono.net'),
 ('Lynyx', 'lynyx.io'),
 ('Harum Retail SARL', 'harum.io'),
 ('Somono Stone', 'mail.somono.com'),
 ('Pivyn Maritime', 'pivyn.org'),
 ('Praeora Advisors AS', 'mail.praeora.org'),
 ('Nivet Supply', 'nivet.io'),
 ('Epsos Pvt Ltd', 'epsos.com'),
 ('Averano Logistics Oy', 'mail.averano.net'),
 ('Elvoio', 'mail.elvoio.io'),
 ('Zalaal', 'mail.zalaal.org'),
 ('Otrium', 'mail.otrium.io'),
 ('Viria', 'mail.viria.io'),
 ('Monino Inc.', 'monino.org'),
 ('Lynter PLC', 'mail.lynter.io'),
 ('Dovar Apparel', 'mail.dovar.io'),
 ('Praea Engineering', 'mail.praea.io'),
 ('Kalmivo Robotics', 'kalmivo.org'),
 ('Plenel PLC', 'plenel.io'),
 ('Clyono Engineering', 'mail.clyono.io'),
 ('Plenio Security', 'mail.plenio.org'),
 ('Lynea Sports', 'lynea.io'),
 ('Galet', 'mail.galet.net'),
 ('Glaal', 'glaal.com'),
 ('Brixos', 'mail.brixos.net'),
 ('Klevyx', 'klevyx.io'),
 ('Nexer', 'mail.nexer.net'),
 ('Zenvion Supply Oy', 'zenvion.com'),
 ('Yurono', 'mail.yurono.io'),
 ('Yunono Pets', 'mail.yunono.com'),
 ('Merel Analytics Kft.', 'mail.merel.com'),
 ('Briino LLC', 'briino.io'),
 ('Alvyn ApS', 'mail.alvyn.io'),
 ('Uplium Kft.', 'mail.uplium.net'),
 ('Prisos Motors', 'prisos.com'),
 ('Plenex Supply', 'mail.plenex.com'),
 ('Maven Textiles AG', 'mail.maven.io'),
 ('Praeano Ltd.', 'mail.praeano.org'),
 ('Triono Gardens ApS', 'triono.com'),
 ('Quaria s.r.o.', 'mail.quaria.net'),
 ('Lunyx Devices', 'lunyx.com'),
 ('Inven Textiles', 'mail.inven.net'),
 ('Prisea Imaging', 'mail.prisea.net'),
 ('Zener', 'mail.zener.org'),
 ('Delero Imaging Ltd.', 'delero.io'),
 ('Vireva AG', 'mail.vireva.com'),
 ('Clyion Oy', 'clyion.com'),
 ('Yurex', 'mail.yurex.io'),
 ('Valyx Research SA', 'mail.valyx.io'),
 ('Javio Devices', 'javio.io'),
 ('Glaium Steel Pte Ltd', 'mail.glaium.com'),
 ('Inzyn Audio', 'mail.inzyn.com'),
 ('Rivenino Stone', 'mail.rivenino.org'),
 ('Uvino Sàrl', 'mail.uvino.net'),
 ('Praeeno SA', 'praeeno.net'),
 ('Briea SARL', 'mail.briea.net'),
 ('Zeria Fashion', 'mail.zeria.io'),
 ('Ivorono Steel', 'ivorono.com'),
 ('Ossios Lighting', 'ossios.com'),
 ('Senvis Finance AB', 'mail.senvis.com'),
 ('Praeon Research S.L.', 'praeon.io'),
 ('Kalon Lighting', 'mail.kalon.io'),
 ('Klevyn Steel ApS', 'mail.klevyn.org'),
 ('Cinino Steel Inc.', 'mail.cinino.io'),
 ('Prisum Audio', 'prisum.org'),
 ('Nexalia Pte Ltd', 'nexalia.net'),
 ('Qartexo ApS', 'qartexo.org'),
 ('Solium', 'mail.solium.org'),
 ('Yunor Bio', 'yunor.com'),
 ('Novon SA', 'novon.org'),
 ('Ivoio Health', 'ivoio.net'),
 ('Kalia Pets', 'kalia.net'),
 ('Varano', 'mail.varano.org'),
 ('Kalis Textiles', 'mail.kalis.net'),
 ('Monora Supply Ltd', 'mail.monora.org'),
 ('Pleneva Space AG', 'pleneva.com'),
 ('Yola AB', 'yola.com'),
 ('Triaen', 'triaen.io'),
 ('Trion AB', 'mail.trion.io'),
 ('Joret', 'mail.joret.io'),
 ('Epsino Software', 'epsino.io'),
 ('Merano Textiles Pvt Ltd', 'mail.merano.com'),
 ('Novix Analytics', 'novix.com'),
 ('Rivet GmbH', 'rivet.org'),
 ('Maveva', 'mail.maveva.io'),
 ('Zenel Home', 'zenel.com'),
 ('Lazo AS', 'lazo.net'),
 ('Klevion', 'mail.klevion.io'),
 ('Monix Imaging', 'mail.monix.org'),
 ('Averor Games', 'mail.averor.com'),
 ('Hario Sp. z o.o.', 'hario.net'),
 ('Xero', 'xero.org'),
 ('Galo Toys', 'mail.galo.net'),
 ('Lyntino', 'lyntino.com'),
 ('Pivo Materials', 'pivo.net'),
 ('Praeivo GmbH', 'mail.praeivo.io'),
 ('Winexo Pvt Ltd', 'mail.winexo.com'),
 ('Prisyn Data', 'prisyn.org'),
 ('Brixono Space Sàrl', 'mail.brixono.io'),
 ('Roveis Fashion Inc.', 'mail.roveis.com'),
 ('Upler Tools Sp. z o.o.', 'upler.com'),
 ('Klevor Pharma', 'mail.klevor.net'),
 ('Wavix', 'mail.wavix.org'),
 ('Zalaera Oy', 'zalaera.net'),
 ('Qalyn Networks', 'mail.qalyn.io'),
 ('Luno', 'mail.luno.org'),
 ('Nivium Space NV', 'mail.nivium.io'),
 ('Lazar Labs GmbH', 'lazar.org'),
 ('Arceia', 'arceia.net'),
 ('Averino Maritime Oy', 'averino.com'),
 ('Dovel', 'mail.dovel.net'),
 ('Lazos', 'lazos.io'),
 ('Arceera PLC', 'arceera.com'),
 ('Somium Retail', 'somium.org'),
 ('Vastia Print ApS', 'mail.vastia.io'),
 ('Avereva Software Ltd.', 'mail.avereva.org'),
 ('Umbon Home', 'mail.umbon.com'),
 ('Mona Motors', 'mona.io'),
 ('Wavivo Apparel Ltd.', 'wavivo.org'),
 ('Senveva Logistics', 'mail.senveva.org'),
 ('Novion Kft.', 'mail.novion.net'),
 ('Senvium Pharma', 'senvium.io'),
 ('Gala Tools ApS', 'gala.com'),
 ('Pivix Shipping Pte Ltd', 'pivix.net'),
 ('Inzor SA', 'mail.inzor.net'),
 ('Niveno', 'mail.niveno.org'),
 ('Praeion GmbH', 'mail.praeion.org'),
 ('Nexo', 'nexo.com'),
 ('Upla s.r.o.', 'upla.com'),
 ('Riveneva Apparel', 'riveneva.io'),
 ('Otrexo Sàrl', 'otrexo.com'),
 ('Pivea Apparel', 'pivea.io'),
 ('Ivorero', 'mail.ivorero.org'),
 ('Delvera Security Inc.', 'mail.delvera.net'),
 ('Elvera', 'elvera.io'),
 ('Briano', 'mail.briano.net'),
 ('Luner Sports', 'luner.net'),
 ('Arceio Ltd', 'mail.arceio.com'),
 ('Qalos Shipping Ltd', 'mail.qalos.io'),
 ('Fenano', 'fenano.net'),
 ('Galar', 'mail.galar.com'),
 ('Ivoera', 'mail.ivoera.com'),
 ('Vastea', 'mail.vastea.io'),
 ('Arceis Pets', 'mail.arceis.net'),
 ('Inval GmbH', 'mail.inval.net'),
 ('Klevis Beverages', 'klevis.com'),
 ('Hivio Tools GmbH', 'hivio.org'),
 ('Trio Pvt Ltd', 'mail.trio.com'),
 ('Tivino Technologies', 'tivino.com'),
 ('Calio Research GmbH', 'calio.org'),
 ('Glaal', 'mail.glaal.io'),
 ('Merar Beauty S.A.', 'merar.io'),
 ('Gravet', 'gravet.com'),
 ('Calium S.A.', 'calium.net'),
 ('Elvivo Chem', 'mail.elvivo.net'),
 ('Joriano', 'joriano.net'),
 ('Qartal', 'qartal.io'),
 ('Xerino Inc.', 'mail.xerino.org'),
 ('Quelera', 'mail.quelera.io'),
 ('Praeor Supply', 'praeor.net'),
 ('Senvivo Security PLC', 'mail.senvivo.com'),
 ('Viria s.r.o.', 'viria.org'),
 ('Fenara Beauty', 'mail.fenara.io'),
 ('Quaria Security', 'quaria.org'),
 ('Kaiis', 'kaiis.com'),
 ('Aveara Chem', 'aveara.net'),
 ('Wino Materials', 'wino.net'),
 ('Rivenum AB', 'rivenum.com'),
 ('Harium Technologies GmbH', 'mail.harium.io'),
 ('Otreva Care', 'otreva.io'),
 ('Tivix Kft.', 'tivix.org'),
 ('Yolara', 'yolara.com'),
 ('Qalea S.A.', 'qalea.com'),
 ('Uvinos Tools Oy', 'uvinos.net'),
 ('Lyntino', 'mail.lyntino.org'),
 ('Umbel', 'mail.umbel.net'),
 ('Laza Labs Pte Ltd', 'mail.laza.io'),
 ('Elvoyx', 'elvoyx.com'),
 ('Otral Shipping NV', 'mail.otral.org'),
 ('Terael SL', 'terael.net'),
 ('Clyino', 'clyino.net'),
 ('Quelino Ventures AG', 'mail.quelino.org'),
 ('Vastion LLC', 'mail.vastion.org'),
 ('Lynia Beauty', 'lynia.net'),
 ('Inzum Materials', 'inzum.io'),
 ('Triora', 'triora.net'),
 ('Ivoeno S.L.', 'ivoeno.org'),
 ('Ivoron B.V.', 'ivoron.io'),
 ('Cintael Inc.', 'mail.cintael.org'),
 ('Pivyx Maritime', 'pivyx.com'),
 ('Hivero Inc.', 'mail.hivero.com'),
 ('Quelio Maritime B.V.', 'quelio.io'),
 ('Winion Marine', 'mail.winion.com'),
 ('Zerex Research SL', 'mail.zerex.com'),
 ('Quelet Stone Sp. z o.o.', 'quelet.org'),
 ('Invium', 'invium.org'),
 ('Ivorix', 'ivorix.com'),
 ('Laza', 'mail.laza.com'),
 ('Uvinivo Systems S.A.', 'uvinivo.org'),
 ('Xelos Devices AS', 'xelos.net'),
 ('Delvis AS', 'mail.delvis.org'),
 ('Alvia Care Inc.', 'alvia.com'),
 ('Otreva Software', 'otreva.org'),
 ('Borino Group', 'mail.borino.io'),
 ('Fluxivo s.r.o.', 'mail.fluxivo.com'),
 ('Monion AS', 'mail.monion.com'),
 ('Glaion Sports', 'mail.glaion.io'),
 ('Jorero S.A.', 'mail.jorero.io'),
 ('Yolono AS', 'yolono.com'),
 ('Yuros PLC', 'yuros.com'),
 ('Yolal Systems', 'mail.yolal.org'),
 ('Kalix', 'mail.kalix.org'),
 ('Ivoea Design SA', 'mail.ivoea.com'),
 ('Haros AG', 'haros.net'),
 ('Graeno Systems SL', 'mail.graeno.com'),
 ('Kalero Research', 'kalero.com'),
 ('Nexalum Kft.', 'nexalum.com'),
 ('Dovexo Software', 'mail.dovexo.net'),
 ('Fraxon', 'mail.fraxon.net'),
 ('Praeion', 'mail.praeion.com'),
 ('Varivo AB', 'mail.varivo.io'),
 ('Lunaeno Games SARL', 'mail.lunaeno.org'),
 ('Merora ApS', 'mail.merora.io'),
 ('Clyer Technologies', 'clyer.org'),
 ('Zenera Green AG', 'mail.zenera.net'),
 ('Xelet SA', 'mail.xelet.net'),
 ('Elver NV', 'mail.elver.com'),
 ('Inzyn LLC', 'inzyn.net'),
 ('Nexum Stone Pte Ltd', 'nexum.io'),
 ('Lynera', 'lynera.io'),
 ('Zenvio Games', 'zenvio.org'),
 ('Wavet Pharma', 'wavet.org'),
 ('Hivera', 'hivera.io'),
 ('Fluxet Software Kft.', 'fluxet.com'),
 ('Virion Oy', 'virion.com'),
 ('Rivenia Marine', 'rivenia.io'),
 ('Novos Care', 'mail.novos.io'),
 ('Tivis', 'mail.tivis.org'),
 ('Lunis Consulting S.L.', 'lunis.net'),
 ('Praeivo Fashion AB', 'praeivo.com'),
 ('Mona Consulting', 'mona.org'),
 ('Qalium', 'qalium.net'),
 ('Somino Software GmbH', 'mail.somino.io'),
 ('Lazo', 'mail.lazo.com'),
 ('Rivum BV', 'mail.rivum.net'),
 ('Ossiion Maritime', 'mail.ossiion.com'),
 ('Uvinos Networks S.A.', 'uvinos.io'),
 ('Solis Retail', 'solis.net'),
 ('Triivo Systems', 'mail.triivo.org'),
 ('Quarar Pte Ltd', 'quarar.io'),
 ('Yunivo BV', 'yunivo.org'),
 ('Plenivo PLC', 'mail.plenivo.io'),
 ('Fraxion Partners S.L.', 'mail.fraxion.io'),
 ('Invo SA', 'mail.invo.com'),
 ('Inzino Consulting Pte Ltd', 'inzino.org'),
 ('Nexalal Consulting', 'mail.nexalal.net'),
 ('Winium', 'mail.winium.net'),
 ('Drios', 'drios.net'),
 ('Calos Imaging SA', 'mail.calos.org'),
 ('Joren BV', 'joren.net'),
 ('Epsio Studios PLC', 'epsio.net'),
 ('Fluxium', 'fluxium.com'),
 ('Merel Lighting PLC', 'merel.org'),
 ('Quelel Cloud GmbH', 'mail.quelel.io'),
 ('Fenium', 'mail.fenium.org'),
 ('Yunex Travel', 'mail.yunex.net'),
 ('Novero Steel', 'mail.novero.org'),
 ('Lazora LLC', 'mail.lazora.net'),
 ('Praeium Foods', 'mail.praeium.com'),
 ('Grais Steel', 'mail.grais.com'),
 ('Nexara', 'nexara.org'),
 ('Umbyn AG', 'umbyn.org'),
 ('Somel Pharma Sàrl', 'somel.com'),
 ('Blyxix Finance', 'mail.blyxix.com'),
 ('Kalmor Labs S.A.', 'kalmor.com'),
 ('Waven S.L.', 'waven.com'),
 ('Invex SL', 'invex.io'),
 ('Varen Chem s.r.o.', 'varen.io'),
 ('Joryn PLC', 'mail.joryn.com'),
 ('Cinor Beverages NV', 'mail.cinor.com'),
 ('Somel Pvt Ltd', 'mail.somel.io'),
 ('Someva', 'someva.net'),
 ('Prisano S.A.', 'mail.prisano.io'),
 ('Qalano Sàrl', 'qalano.io'),
 ('Kalmano Steel', 'mail.kalmano.com'),
 ('Cora Beauty', 'cora.io'),
 ('Rivo Pte Ltd', 'mail.rivo.com'),
 ('Lunaera Beauty', 'mail.lunaera.org'),
 ('Nimera Pharma SARL', 'nimera.com'),
 ('Roveex Data', 'roveex.io'),
 ('Triaex Design SL', 'triaex.com'),
 ('Terais', 'terais.org'),
 ('Altis Design Sp. z o.o.', 'altis.com'),
 ('Render', 'render.com'),
 ('Arceel', 'arceel.org'),
 ('Kalum SARL', 'mail.kalum.net'),
 ('Nivyx LLC', 'mail.nivyx.io'),
 ('Altix Engineering AB', 'altix.io'),
 ('Kalar Health SARL', 'mail.kalar.org'),
 ('Merero Group', 'merero.org'),
 ('Rivenio Technologies', 'mail.rivenio.org'),
 ('Lyner Kft.', 'lyner.io'),
 ('Yurero Pte Ltd', 'yurero.org'),
 ('Zyphum Supply', 'zyphum.com'),
 ('Lyntia Steel Inc.', 'mail.lyntia.net'),
 ('Elvoyn Engineering', 'elvoyn.com'),
 ('Varos Sports Pte Ltd', 'varos.io'),
 ('Wineno Audio', 'wineno.net'),
 ('Uplora', 'mail.uplora.com'),
 ('Brixeno Toys', 'brixeno.com'),
 ('Dovis Dynamics Oy', 'mail.dovis.io'),
 ('Kinon Care', 'kinon.io'),
 ('Qalon Logistics Sp. z o.o.', 'mail.qalon.io'),
 ('Nivium Capital AG', 'nivium.io'),
 ('Delvix Maritime Pvt Ltd', 'mail.delvix.net'),
 ('Altea Audio LLC', 'mail.altea.com'),
 ('Pivion Sp. z o.o.', 'pivion.com'),
 ('Kaios Software Ltd.', 'kaios.net'),
 ('Jorexo Electronics', 'mail.jorexo.io'),
 ('Elvoo Logistics ApS', 'elvoo.org'),
 ('Triaor Foods', 'mail.triaor.net'),
 ('Fluxano Networks', 'mail.fluxano.io'),
 ('Quarivo', 'quarivo.com'),
 ('Triaex Group', 'mail.triaex.io'),
 ('Fraxara Cloud', 'fraxara.com'),
 ('Hivara Bio', 'mail.hivara.net'),
 ('Galera', 'mail.galera.io'),
 ('Zerion Studios', 'mail.zerion.com'),
 ('Meryn BV', 'mail.meryn.net'),
 ('Ivoo', 'mail.ivoo.org'),
 ('Arceano SA', 'mail.arceano.io'),
 ('Alta', 'alta.org'),
 ('Clyera Inc.', 'mail.clyera.net'),
 ('Borino', 'mail.borino.net'),
 ('Umbyn SA', 'umbyn.com'),
 ('Alvia', 'mail.alvia.com'),
 ('Klevo Dynamics', 'klevo.org'),
 ('Klevo Print', 'klevo.io'),
 ('Qartara Logistics B.V.', 'qartara.net'),
 ('Kalmyx', 'mail.kalmyx.org'),
 ('Triaos Systems', 'mail.triaos.com'),
 ('Xelyn Digital', 'mail.xelyn.net'),
 ('Cintaano PLC', 'mail.cintaano.io'),
 ('Oryor Ltd.', 'mail.oryor.io'),
 ('Oryia AS', 'mail.oryia.io'),
 ('Nexaler GmbH', 'nexaler.org'),
 ('Otrera Apparel GmbH', 'mail.otrera.com'),
 ('Brixono Sàrl', 'mail.brixono.com'),
 ('Rendo', 'mail.rendo.net'),
 ('Blyxano Imaging GmbH', 'blyxano.com'),
 ('Rendivo Group', 'rendivo.net'),
 ('Wavino BV', 'mail.wavino.com'),
 ('Prisono AB', 'prisono.net'),
 ('Caleva', 'mail.caleva.net'),
 ('Elvoea Steel GmbH', 'elvoea.net'),
 ('Zyphum AG', 'zyphum.org'),
 ('Cintaexo AG', 'mail.cintaexo.org'),
 ('Galium', 'mail.galium.com'),
 ('Inzero', 'mail.inzero.net'),
 ('Ivoria S.L.', 'ivoria.org'),
 ('Glaal Ltd.', 'glaal.io'),
 ('Alvivo Supply Inc.', 'alvivo.com'),
 ('Senval', 'mail.senval.org'),
 ('Kalmex', 'kalmex.io'),
 ('Nexalio Robotics Sp. z o.o.', 'mail.nexalio.com'),
 ('Epsos Consulting ApS', 'mail.epsos.net'),
 ('Aveano', 'aveano.io'),
 ('Gravara SARL', 'gravara.com'),
 ('Senvera Print Ltd', 'senvera.io'),
 ('Trial', 'mail.trial.org'),
 ('Galora Fashion', 'galora.com'),
 ('Javia Pets', 'mail.javia.org'),
 ('Bora Systems Sp. z o.o.', 'bora.net'),
 ('Valon Gardens Sp. z o.o.', 'mail.valon.net'),
 ('Kalmio', 'mail.kalmio.net'),
 ('Nexalea PLC', 'mail.nexalea.io'),
 ('Nexino', 'mail.nexino.io'),
 ('Triaivo Research NV', 'mail.triaivo.org'),
 ('Borero AB', 'mail.borero.org'),
 ('Zerum Finance', 'zerum.net'),
 ('Teraon SARL', 'teraon.io'),
 ('Zyphon', 'zyphon.org'),
 ('Corer Games Ltd', 'mail.corer.com'),
 ('Mavon Lighting S.L.', 'mavon.com'),
 ('Triis Space', 'triis.io'),
 ('Lyner Ventures', 'mail.lyner.com'),
 ('Senvel', 'senvel.io'),
 ('Lunor Sàrl', 'lunor.com'),
 ('Xanora Sàrl', 'xanora.org'),
 ('Clyis', 'clyis.org'),
 ('Vastar BV', 'mail.vastar.org'),
 ('Qartero AG', 'mail.qartero.com'),
 ('Oryara AG', 'oryara.com'),
 ('Hiveo s.r.o.', 'mail.hiveo.com'),
 ('Kalmara Pharma LLC', 'mail.kalmara.io'),
 ('Alvum Research', 'alvum.org'),
 ('Dela', 'dela.io'),
 ('Kalar Logistics', 'kalar.com'),
 ('Otrel GmbH', 'mail.otrel.org'),
 ('Quelono', 'mail.quelono.com'),
 ('Noveno SARL', 'mail.noveno.com'),
 ('Pivono Group', 'pivono.com'),
 ('Vastis Health', 'vastis.com'),
 ('Quarer Group', 'mail.quarer.org'),
 ('Lynia Group Sàrl', 'lynia.com'),
 ('Brixos', 'mail.brixos.io'),
 ('Uvinexo', 'mail.uvinexo.org'),
 ('Fenen s.r.o.', 'mail.fenen.com'),
 ('Uvineno', 'uvineno.io'),
 ('Blyxet', 'blyxet.org'),
 ('Fluxia Kft.', 'fluxia.net'),
 ('Harel Robotics', 'mail.harel.com'),
 ('Ivoex Motors NV', 'ivoex.io'),
 ('Zerara Fashion', 'mail.zerara.io'),
 ('Delvo Games', 'mail.delvo.com'),
 ('Arceet AB', 'arceet.com'),
 ('Glaex Chem', 'mail.glaex.org'),
 ('Elvois Textiles AB', 'elvois.net'),
 ('Valor Travel', 'valor.net'),
 ('Zalaora Retail', 'zalaora.net'),
 ('Nimeva Pvt Ltd', 'mail.nimeva.org'),
 ('Renden Cloud', 'mail.renden.io'),
 ('Vastix ApS', 'mail.vastix.io'),
 ('Somivo', 'mail.somivo.net'),
 ('Kaiara Pvt Ltd', 'kaiara.io'),
 ('Kinar Partners', 'kinar.io'),
 ('Viron', 'viron.com'),
 ('Velon Engineering', 'velon.com'),
 ('Calar', 'calar.org'),
 ('Zalaix Sàrl', 'zalaix.net'),
 ('Brixor Steel', 'mail.brixor.io'),
 ('Blyxar', 'blyxar.com'),
 ('Elvo Electronics ApS', 'mail.elvo.io'),
 ('Quarano Oy', 'quarano.net'),
 ('Xanyx Finance ApS', 'xanyx.io'),
 ('Gravexo Analytics Ltd', 'gravexo.io'),
 ('Aveono', 'aveono.net'),
 ('Yolero Data', 'mail.yolero.org'),
 ('Lynara AS', 'mail.lynara.net'),
 ('Nexalix', 'mail.nexalix.com'),
 ('Yolix Marine Inc.', 'yolix.net'),
 ('Lunum', 'mail.lunum.org'),
 ('Mavino Capital', 'mail.mavino.io'),
 ('Rivenara', 'mail.rivenara.net'),
 ('Umbara', 'umbara.org'),
 ('Somar Foods Inc.', 'mail.somar.io'),
 ('Monis Apparel B.V.', 'mail.monis.io'),
 ('Fraxo Ltd.', 'fraxo.org'),
 ('Rivono Bio LLC', 'mail.rivono.io'),
 ('Umbex Fashion', 'mail.umbex.com'),
 ('Uvinino Research Pvt Ltd', 'uvinino.com'),
 ('Joria Design', 'mail.joria.org'),
 ('Yoler Maritime Ltd', 'yoler.com'),
 ('Qalor Technologies', 'qalor.org'),
 ('Jorieno GmbH', 'mail.jorieno.org'),
 ('Arceono', 'mail.arceono.org'),
 ('Roveino', 'roveino.com'),
 ('Klevix', 'klevix.com'),
 ('Fluxar Group GmbH', 'mail.fluxar.com'),
 ('Rendeva Marine PLC', 'rendeva.io'),
 ('Tivix Cloud', 'tivix.io'),
 ('Mavix', 'mavix.com'),
 ('Valono', 'mail.valono.io'),
 ('Quareva', 'quareva.com'),
 ('Trial Tools', 'trial.net'),
 ('Joriero', 'joriero.io'),
 ('Uplion', 'uplion.org'),
 ('Virium Travel PLC', 'mail.virium.io'),
 ('Corora Data GmbH', 'mail.corora.com'),
 ('Zenvea Audio AG', 'zenvea.org'),
 ('Calyx Technologies', 'calyx.com'),
 ('Xerino Beauty', 'xerino.io'),
 ('Nexor Imaging SARL', 'mail.nexor.io'),
 ('Kalio', 'mail.kalio.io'),
 ('Cintais Digital', 'cintais.org'),
 ('Yuren Consulting Oy', 'yuren.io'),
 ('Fluxer', 'mail.fluxer.io'),
 ('Teraono Sports', 'mail.teraono.net'),
 ('Jolora Technologies', 'mail.jolora.org'),
 ('Hivea Security', 'hivea.net'),
 ('Wavor AB', 'wavor.com'),
 ('Wavio Pvt Ltd', 'mail.wavio.net'),
 ('Hivor', 'hivor.com'),
 ('Dover Textiles', 'mail.dover.io'),
 ('Kinora AB', 'mail.kinora.com'),
 ('Lunaivo', 'mail.lunaivo.net'),
 ('Mavum Security', 'mavum.com'),
 ('Yurera', 'mail.yurera.io'),
 ('Hivix', 'hivix.org'),
 ('Cinono Motors Sàrl', 'cinono.net'),
 ('Kalal Sp. z o.o.', 'kalal.org'),
 ('Oryen Imaging AS', 'oryen.org'),
 ('Merer S.L.', 'merer.net'),
 ('Brion Ventures', 'brion.org'),
 ('Yurix Logistics', 'mail.yurix.net'),
 ('Oryyn Materials', 'mail.oryyn.org'),
 ('Kalum SARL', 'kalum.com'),
 ('Qarto AB', 'qarto.com'),
 ('Brieno LLC', 'brieno.net'),
 ('Cintaor s.r.o.', 'mail.cintaor.net'),
 ('Aveos', 'aveos.net'),
 ('Zenveva', 'mail.zenveva.net'),
 ('Driion Group Kft.', 'driion.com'),
 ('Piver Home', 'mail.piver.io'),
 ('Galar Tools', 'galar.com'),
 ('Nexalyx Security AB', 'nexalyx.org'),
 ('Corion Imaging', 'corion.io'),
 ('Xanal Design B.V.', 'mail.xanal.com'),
 ('Lunaum LLC', 'mail.lunaum.com'),
 ('Elvoen Materials SA', 'elvoen.net'),
 ('Lazeno Home S.A.', 'lazeno.org'),
 ('Jorio', 'jorio.com'),
 ('Joron Fashion', 'mail.joron.io'),
 ('Gravono Pvt Ltd', 'gravono.org'),
 ('Vastia Fashion Pvt Ltd', 'mail.vastia.net'),
 ('Nexano Electronics SA', 'nexano.com'),
 ('Qartara Marine Ltd', 'mail.qartara.io'),
 ('Xanino', 'mail.xanino.net'),
 ('Uplano ApS', 'mail.uplano.org'),
 ('Otren Imaging Pte Ltd', 'mail.otren.com'),
 ('Jorar Kft.', 'jorar.org'),
 ('Oryer Oy', 'mail.oryer.net'),
 ('Lyntono Robotics SL', 'mail.lyntono.com'),
 ('Invera Sàrl', 'mail.invera.com'),
 ('Kalum Analytics Oy', 'mail.kalum.com'),
 ('Veleno Bio PLC', 'mail.veleno.org'),
 ('Uplivo Textiles', 'uplivo.net'),
 ('Jorieno', 'jorieno.org'),
 ('Noven Sàrl', 'noven.org'),
 ('Noven Engineering Sp. z o.o.', 'mail.noven.net'),
 ('Uviner GmbH', 'uviner.net'),
 ('Zenar Kft.', 'zenar.net'),
 ('Pivio Motors', 'mail.pivio.org'),
 ('Kalmet', 'kalmet.org'),
 ('Zenvon AS', 'zenvon.org'),
 ('Xelyx', 'mail.xelyx.org'),
 ('Lunaora', 'lunaora.net'),
 ('Drieno', 'mail.drieno.net'),
 ('Jorivo Inc.', 'jorivo.io'),
 ('Kaiara AS', 'mail.kaiara.net'),
 ('Cintaora Textiles', 'cintaora.org'),
 ('Vaston S.A.', 'vaston.org'),
 ('Nexalono Sp. z o.o.', 'mail.nexalono.net'),
 ('Rivar S.A.', 'mail.rivar.io'),
 ('Briet', 'briet.org'),
 ('Javora Gardens AG', 'javora.com'),
 ('Averyx AB', 'mail.averyx.com'),
 ('Elvoor Foods Ltd', 'elvoor.net'),
 ('Hiveea Beverages AS', 'mail.hiveea.net'),
 ('Plenexo AG', 'mail.plenexo.io'),
 ('Prisia', 'prisia.org'),
 ('Zenvio Electronics', 'mail.zenvio.io'),
 ('Viron', 'viron.org'),
 ('Fener Beverages', 'fener.com'),
 ('Nexaler Inc.', 'mail.nexaler.io'),
 ('Hiveexo', 'mail.hiveexo.com'),
 ('Niver Marine SA', 'niver.io'),
 ('Valera Advisors', 'mail.valera.io'),
 ('Arceon', 'arceon.com'),
 ('Nexal Gardens', 'nexal.com'),
 ('Zalayn Bio', 'zalayn.net'),
 ('Fluxeno Tools PLC', 'fluxeno.org'),
 ('Hivix Beauty', 'hivix.com'),
 ('Yolano Travel S.A.', 'yolano.io'),
 ('Velis Bio S.A.', 'velis.org'),
 ('Roveexo Ltd', 'mail.roveexo.io'),
 ('Invea Networks', 'mail.invea.net'),
 ('Xelivo Ventures', 'mail.xelivo.io'),
 ('Meryn', 'meryn.org'),
 ('Kalexo Partners', 'mail.kalexo.org'),
 ('Delora PLC', 'delora.org'),
 ('Cinea Robotics', 'cinea.io'),
 ('Uvinen Foods', 'uvinen.io'),
 ('Uplyn Technologies NV', 'mail.uplyn.io')
]
